name: ffmpeg
version: 3.1
summary: Tools for transcoding, streaming and playing of multimedia files
description: |
  FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
  mux, demux, stream, filter and play pretty much anything that humans and
  machines have created. It supports the most obscure ancient formats up to the
  cutting edge.
  This package contains
    ffmpeg - a command line tool to convert multimedia files between formats
    ffserver - a multimedia streaming server for live broadcasts
    ffplay - a simple media player based on SDL and the FFmpeg libraries
    ffprobe - a simple multimedia stream analyzer
    qt-faststart - a utility to rearrange Quicktime files
confinement: devmode
# ffcfstress ffmpeg ffmpeg2theora ffmvforce ffplay ffprobe ffserver ffset fftest

apps:
  ffmpeg:
    command: ffmpeg
    plugs: [home]
  #server:
    #command: ffserver
    #plugs: [home]
  #play:
    #command: ffplay
    #plugs: [home]
  #probe:
    #command: ffprobe
    #plugs: [home]
  #faststart:
    #command: qt-faststart
    #plugs: [home]

parts:
  ffmpeg:
    source: ./
    plugin: autotools
    configflags:
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-ffserver
      - --enable-gpl
      - --enable-libass
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libopus
      - --enable-libtheora
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libx264
      - --enable-libx265
      - --enable-nonfree
      - --cpu=native
      - --enable-pthreads
      - --enable-bzlib
      - --enable-nvenc
      - --enable-libdc1394
      - --enable-frei0r
      - --enable-gnutls
      - --enable-libgsm
      - --enable-librtmp
      - --enable-libopencv
      - --enable-libopenjpeg
      - --enable-libpulse
      - --enable-libschroedinger
      - --enable-libspeex
      - --enable-vaapi
      - --enable-vdpau
      - --enable-zlib
      - --enable-libfdk-aac
      - --enable-swscale
      - --enable-libcdio
      - --enable-x11grab
      - --enable-libxvid
      - --enable-libopencore-amrnb
      - --enable-version3
      - --enable-libvo-amrwbenc
    organize:
        usr/local/bin/: bin/
    build-packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - g++
      - git
      - libass-dev
      - libfreetype6-dev
      - libmp3lame-dev
      - libopus-dev
      - libsdl1.2-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - make
      - pkg-config
      - texinfo
      - yasm
      - zlib1g-dev
      # ////////////////////////apt-rdepends///////////////////////
      - ffmpeg
      - libavutil-ffmpeg54
      - libc6
      - libgcc1
      - gcc-6-base
      - libcrystalhd3
      - libstdc++6
      - gcc-5-base
      - multiarch-support
      - libgsm1
      - liblzma5
      - libmp3lame0
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopus0
      - libschroedinger-1.0-0
      - liborc-0.4-0
      - libshine3
      - libspeex1
      - libswresample-ffmpeg1
      - libsoxr0
      - libgomp1
      - libtheora0
      - libogg0
      - libtwolame0
      - libva1
      - libvo-aacenc0
      - libvo-amrwbenc0
      - libvorbis0a
      - libvorbisenc2
      - libvpx1
      - libwavpack1
      - libwebp5
      - libx264-148
      - libx265-79
      - libnuma1
      - libxvidcore4
      - libzvbi0
      - libpng12-0
      - zlib1g
      - libzvbi-common
      - libavcodec-ffmpeg56
      - libopenjpeg5
      - libsnappy1v5
      - libvpx3
      - libavdevice-ffmpeg56
      - libasound2
      - libasound2-data
      - libavc1394-0
      - libraw1394-11
      - libavfilter-ffmpeg5
      - libass5
      - libfontconfig1
      - fontconfig-config
      - fonts-dejavu-core
      - fonts-freefont-ttf
      - gsfonts-x11
      - gsfonts
      - xfonts-utils
      - libfontenc1
      - libfreetype6
      - libxfont1
      - libbz2-1.0
      - x11-common
      - lsb-base
      - xfonts-encodings
      - ttf-bitstream-vera
      - ucf
      - coreutils
      - libacl1
      - libattr1
      - libselinux1
      - libpcre3
      - debconf
      - perl-base
      - dpkg
      - tar
      - libexpat1
      - libfribidi0
      - libharfbuzz0b
      - libglib2.0-0
      - libffi6
      - libgraphite2-3
      - libavformat-ffmpeg56
      - libbluray1
      - libxml2
      - libicu55
      - libgme0
      - libgnutls30
      - libgmp10
      - libhogweed4
      - libnettle6
      - libidn11
      - libp11-kit0
      - libtasn1-6
      - libmodplug1
      - librtmp1
      - libssh-gcrypt-4
      - libgcrypt20
      - libgpg-error0
      - libgssapi-krb5-2
      - libcomerr2
      - libk5crypto3
      - libkrb5support0
      - libkrb5-3
      - libkeyutils1
      - libavresample-ffmpeg2
      - libbs2b0
      - libflite1
      - libopencv-core2.4v5
      - libgl1-mesa-glx
      - libdrm2
      - libgl1-mesa-dri
      - libdrm-amdgpu1
      - libdrm-intel1
      - libpciaccess0
      - libdrm-nouveau2
      - libdrm-radeon1
      - libelf1
      - libllvm3.8
      - libedit2
      - libbsd0
      - libtinfo5
      - libglapi-mesa
      - libudev1
      - libx11-6
      - libx11-data
      - libxcb1
      - libxau6
      - libxdmcp6
      - libx11-xcb1
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-sync1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxshmfence1
      - libxxf86vm1
      - libtbb2
      - libopencv-imgproc2.4v5
      - libpostproc-ffmpeg53
      - libswscale-ffmpeg3
      - libzmq5
      - libsodium18
      - libcaca0
      - libncursesw5
      - libslang2
      - libcdio-cdda1
      - libcdio13
      - libcdio-paranoia1
      - libdc1394-22
      - libusb-1.0-0
      - libiec61883-0
      - libjack-jackd2-0
      - libsamplerate0
      - libopenal1
      - libopenal-data
      - libpulse0
      - libasyncns0
      - libdbus-1-3
      - libsystemd0
      - libjson-c2
      - libsndfile1
      - libflac8
      - libwrap0
      - libsdl1.2debian
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxv1
      # - libvdpau1
